### ISSUE TITLE
`(cat rts.c; ./vm run effectively.hs) > lonely.c` is waiting for stdin?

### ISSUE THREAD

**Issue by tommythorn** [blynn/compiler#5]
Ben, this is an amazing project that I'm still wrapping my head around.

I spotted a curious issue Ubuntu 21.04/x86_64 which might be a documentation issue.  The README.adoc has

```
  $ (cat rts.c; ./vm run effectively.hs) > lonely.c
  $ cc -O2 lonely.c -o lonely
```

but AFAICT, the first command is waiting for stdin.  (Giving in an ^D makes it proceed).

**Comment by blynn** [comment]
Thanks!

Yes, this is a documentation issue that I'll fix soon. I didn't copy and paste from the Makefile correctly. It should be `(cat rts.c; ./vm run effectively.hs < lonely.hs) > lonely.c`.

**Comment by blynn** [comment]
Just pushed the fix.
