### ISSUE TITLE
Dual-licensed with BSD3, pretty please

### ISSUE THREAD

**Issue by av86743** [blynn/compiler#8]
Dear Dr Lynn,

Could you possibly dual-license sources of you amazing Haskell compiler with an MIT-class license, like BSD3?  Subdirectory `inn` would suffice.  Dual-licensing sources to boot until `party2` and `Makefile` would be even more nice.

Thank you in advance,
@av86743

**Comment by blynn** [comment]
Done.

(I don't check my github messages that often by the way; email is faster.)
